services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=security_demo'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=user'
      - 'PGDATA=/data/postgres'
    volumes:
      - db:/data/postgres
    ports:
      - '5432:5432'

volumes:
  db:
  pgadmin-data: